name: Run Autify Web Test

on:
  workflow_dispatch:  # 手動でトリガーするためのイベント

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Autify Test
        uses: autifyhq/actions-web-test-run@v2
        with:
          access-token: ${{ secrets.AUTIFY_WEB_ACCESS_TOKEN }}
          autify-test-url: https://app.autify.com/projects/111/test_plans/914333
